### ISSUE TITLE
[QUESTION] Is frankenphp can be use to pipelines ?

### ISSUE THREAD

**Issue by ezekel** [dunglas/frankenphp#1000]
Hi,

Is it possible frankenphp can be use to my pipelines github ?

Thank you in advance.

**Comment by withinboredom** [comment]
Can you explain more about what you are asking?

**Comment by dunglas** [comment]
If you mean, using FrankenPHP in a GitHub Actions pipeline, yes, it's quite easy to do.
Here is an example of how Symfony does it: https://github.com/symfony/symfony/blob/7.2/.github/workflows/integration-tests.yml#L121-L130

**Comment by ezekel** [comment]
Thank you is this also can be use to bitbucket pipelines ?

**Comment by ezekel** [comment]
> Can you explain more about what you are asking?

I mean can I also use the image to bitbucket pipelines

https://www.atlassian.com/software/bitbucket/features/pipelines

**Comment by withinboredom** [comment]
> I mean can I also use the image to bitbucket pipelines

Yes, we do this at work:

```yaml
definitions:
  steps:
    - step: &build-and-test
        name: Build and Test
        script:
          - echo ${DOCKER_HUB_PASSWORD} | docker login --username "$DOCKER_HUB_USER" --password-stdin
          - IMAGE_NAME=${IMAGE_NAME}:commit-${BITBUCKET_COMMIT}
          - docker build . --file Dockerfile --tag ${IMAGE_NAME}-tests --target tests
          - docker build . --file Dockerfile --tag ${IMAGE_NAME} --target production
          - docker push ${IMAGE_NAME}
        services:
          - docker
        caches:
          - docker

pipelines:
  default:
    - parallel:
        - step: *build-and-test
        - step:
            name: Lint the Dockerfile
            image: hadolint/hadolint:latest-debian
            script:
              - hadolint -t error Dockerfile
```

Where the Dockerfile builds from a frankenphp image.

Does that help answer your question?
