### ISSUE TITLE
Docker fail "exited with code 139" with Laravel Octane and Xdebug

### ISSUE THREAD

**Issue by Macek007** [dunglas/frankenphp#1051]
### What happened?

First of all, this is not actually a bug, but I spent a lot of time on it, so I'm documenting my issues here for future reference. You can close this issue immediately.

I installed Laravel Octane with FrankenPHP for the first time. I followed the tutorials from both projects. I modified the official Docker image `dunglas/frankenphp` with my extensions, including XDebug, but it was unstable, and sometimes the Docker container `exited with code 139`. Whenever I started Clockwork (a debug tool), the container would always exit within a few seconds. However, with `xdebug.mode=off`, there were no problems.

The issue was related to the `compose.yaml` file on the Laravel site: [Laravel Octane Documentation](https://laravel.com/docs/11.x/octane), which looks like this:

```yaml
services:
  frankenphp:
    build:
      context: .
    entrypoint: php artisan octane:frankenphp --workers=1 --max-requests=1
    ports:
      - "8000:8000"
    volumes:
      - .:/app
```

After hours of research and experiments, I removed the parameters `--workers=1 --max-requests=1`, and it ran without any problems.

P.S. FrankenPHP seems to have significantly boosted my project’s performance. Great job!

### Build Type

Docker (Debian Bookworm)

### Worker Mode

Yes

### Operating System

macOS

### CPU Architecture

Apple Silicon

### PHP configuration

```shell
xdebug.log=/app/storage/logs/xdebug.log
xdebug.mode=debug
```
