### ISSUE TITLE
Frankenphp keeps caching the response

### ISSUE THREAD

**Issue by ezekel** [dunglas/frankenphp#1079]
Hi,

I have Laravel api that returns simple text when I use Postman on the first request and second request without changing the API response will reponse immediately, but when I edit the API like this 'Hello frank2'; it takes ~2-3 seconds, then if I will request again without editing it will return immediately then if I edit again it will return 2-3 seconds. I tried also my nuxt app same result it will take 2-3 seconds. 

Does Frankenphp is caching my response? or is there some configuration I missed?

```
Route::get('/books', function (Request $request) {
    return 'Hello frank1';
})->middleware('auth:sanctum');
```

here is my full dockerfile 

```
FROM dunglas/frankenphp:1.2.5-builder-php8.2.24-bookworm


RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
RUN rm /bin/sh && ln -s /bin/bash /bin/sh


RUN install-php-extensions \
    pdo_mysql \
    gd \
    intl \
    zip \
    opcache\
    pcntl\
    @composer


RUN apt-get update && apt-get install -y curl \
    && mkdir -p /root/.nvm \
    && export NVM_DIR="/root/.nvm" \
    && curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash \
    && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" \
    && nvm install --lts \
    && nvm use --lts \
    && npm --version \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && apt-get update \
    && apt-get install -y npm


WORKDIR /app

COPY . /app


EXPOSE 5173

ENTRYPOINT ["php", "artisan", "octane:frankenphp", "--watch"]

```

here is my docker-compose

```
    php:
        container_name: larabells.local
        build:
            context: .
            dockerfile: ./docker/web.dockerfile
        image: larabells

        ports:
            - "80:80"
            - "8000:8000"
            - "443:443"
            - "443:443/udp" # HTTP/3
            - "5173:5173"
        volumes:
            - .:/app

        entrypoint: php artisan octane:frankenphp  --watch   --workers=1 --max-requests=1000 --host=larabells.local --port=80  --admin-port=2019
        environment:
            - SERVER_NAME=larabells.local
        env_file:
            - ./.env
 ```  

In postman test

![image](https://github.com/user-attachments/assets/f8757950-f4f5-40a8-9a72-1787880d4932)

Thank you in advance
