### ISSUE TITLE
Error Laravel Docker Deployment

### ISSUE THREAD

**Issue by oxzman** [dunglas/frankenphp#1128]
### What happened?

i am following this [https://frankenphp.dev/docs/production/](production docs) and want to deploy laravel app in VPS Ubuntu 20.04

i go to laravel root directory and create Dockerfile
```
FROM dunglas/frankenphp

RUN install-php-extensions \
    common \
    bcmatch \
    curl \
    mbstring \
    mysql \
    xml \
    zip 

# If you want to disable HTTPS, use this value instead:
ENV SERVER_NAME=:80
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
COPY . /app
```

then i create compose.yaml inside laravel root app too
```
services:
  php:
    image: dunglas/frankenphp
    restart: always
    ports:
      - "80:80" # HTTP
    volumes:
      - caddy_data:/data
      - caddy_config:/config

# Volumes needed for Caddy certificates and configuration
volumes:
  caddy_data:
  caddy_config:
```

as i am using cloudflare, i think dont need https connection to VPS.

when i access it using public ip  it showing error on browser:
```
ERR_CONNECTION_RESET
```

if access using domain pointing from cloudflare show error:
```
ERR_TOO_MANY_REDIRECTS
```
in cloudflare i am enable use HTTPS

### Build Type

Docker (Alpine)

### Worker Mode

Yes

### Operating System

GNU/Linux

### CPU Architecture

x86_64

### PHP configuration

```shell
unable to find phpinfo(), since the server is not accessible
```
