### ISSUE TITLE
Running on a different port redirects to :80

### ISSUE THREAD

**Issue by vinyll** [dunglas/frankenphp#134]
Run a different port is very convenient for development as it does not require to run with sudo and does not conflict with existing server.

However running the following does not up so well:

```
docker run -v $PWD:/app/public \
    -p 8080:80 -p 443:443 \
    dunglas/frankenphp
```

shoud allow to open a browser and read the app from `http://localhost:8080`.
However we get redirected to `https://localhost`.

**Comment by withinboredom** [comment]
It sounds like you have a Caddyfile telling it to use https, and it is redirecting to https (port 443).

**Comment by sashaaro** [comment]
You can try specify `SERVER_NAME` env
```yaml
services: 
  frankenphp:
    image: dunglas/frankenphp:latest-alpine
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - CADDY_DEBUG=debug
      - DEBUG=debug
      - FRANKENPHP_CONFIG="worker ./public/index.php"
      - APP_RUNTIME=Runtime\FrankenPhpSymfony\Runtime
      - SERVER_NAME=:8080
    ports:
      - 8080:8080
```
