### ISSUE TITLE
Enabling/adding PHP extensions

### ISSUE THREAD

**Issue by jasonmccallister** [dunglas/frankenphp#138]
What is the best way to add PHP extensions? Once approach I enjoy from Bref is how it [includes the extensions](https://bref.sh/docs/environment/php.html#extensions) but disables them. Are there plans to include enabling/disabling extensions like Postgres?

**Comment by jasonmccallister** [comment]
I did a little bit of code diving into the container build (Dockerfile) and saw the image ships with [mlocati/docker-php-extension-installer](https://github.com/mlocati/docker-php-extension-installer). So I wrapped the dunglas/frankenphp image with my own `Dockerfile`:

```
FROM dunglas/frankenphp
RUN apt-get update -y && rm -rf /var/lib/apt/lists/*
RUN install-php-extensions pdo_pgsql
COPY Caddyfile /etc/Caddyfile
```

Then I made a `docker-compose.yaml` file with the following:

```
version: "3.7"
services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    image: my-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./Caddyfile:/etc/Caddyfile # really only used to tweak/override the Caddy config for development
    environment:
      SERVER_NAME: ":8000" # override the Caddyfile to use a port instead of a domain
    env_file: .env
volumes:
  db_data:
```
