### ISSUE TITLE
Trying to get Xdebug to work, but it just responds to requests containing index.php

### ISSUE THREAD

**Issue by je-schindler** [dunglas/frankenphp#1440]
Hey, 

I'm trying to get frankenphp together with Laravel Octane and Xdebug to work (hosted locally). Therefore, I'm running frankenphp in a Docker container, mounted everything important and set the path mappings in my PHPStorm instance.

However my breakpoints are not getting triggered, when calling a page like https://localhost/{laravel-route}, although the page is working. 
However, breakpoints are triggered, when calling the page like https://localhost/index.php/{laravel-route}. I tried already to write rewrites in the Caddyfile, but it's not working for some reason.

Does anyone have an advice?

Dockerfile:
```
FROM dunglas/frankenphp

RUN install-php-extensions \
    pcntl \
    bcmath \
    gd \
    opcache \
    pdo_mysql \
    xdebug \
    zip;

ENTRYPOINT ["/bin/sh", "-c" , "php -d variables_order=EGPCS artisan octane:start --server=frankenphp --host=localhost --port=443 --admin-port=2019 --https"]
```

docker-compose.yml (based on sail):
```
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.4
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.4/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - frankenphp
            - mariadb
            - mailpit
    frankenphp:
        build:
            context: docker/frankenphp
        ports:
            - '443:443'
            - '443:443/udp'
        environment:
            XDG_CONFIG_HOME:  /app/config
            XDG_DATA_HOME:  /app/data
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            CADDY_SERVER_EXTRA_DIRECTIVES: 'rewrite * /index.php/{path}?{query}'
        volumes:
            - .:/app
        networks:
          - sail
    mariadb:
        image: 'mariadb:11.7'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        command: --max_allowed_packet=1073741824
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sail-mariadb:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
          - '8025:8025'
        networks:
          - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-mariadb:
        driver: local
```
