### ISSUE TITLE
Error when starting FrankenPHP since new build related to mercure

### ISSUE THREAD

**Issue by MirakuSan** [dunglas/frankenphp#204]
Hello,

Since the new build (a few hours ago) I can't seem to be able to start my frankenphp container.

The error seems to be related to Mercure, here is what I have when running `docker compose logs frankenphp` :

```shell
frankenphp  | Error: loading initial config: loading new config: loading http app module: provision http: server srv0: setting up route handlers: route 0: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 0: loading handler modules: position 0: loading module 'subroute': provision http.handlers.subroute: setting up subroutes: route 0: loading handler modules: position 1: loading module 'mercure': provision http.handlers.mercure: a JWT key for publishers must be provided
```

Here is my docker-compose.yml conf 
```yaml
    frankenphp:
        container_name: ${COMPOSE_PROJECT_NAME}_frankenphp
        build:
            dockerfile: ./devops/frankenphp/Dockerfile
            context: .
            args:
                APP_ENV: ${APP_ENV:-dev}
        environment:
            SERVER_NAME: ${SERVER_NAME:-localhost}
        restart: unless-stopped
        volumes:
            - ./:/app
```

```Dockerfile
ARG APP_ENV=prod

FROM dunglas/frankenphp as frankenphp_prod
ENV FRANKENPHP_CONFIG="worker ./public/index.php"

FROM dunglas/frankenphp as frankenphp_dev
ENV FRANKENPHP_CONFIG=""

FROM frankenphp_${APP_ENV}

ARG APP_ENV=prod

RUN if [ "$APP_ENV" = "dev" ]; then \
      apt update && \
      apt install -y \
        python3-pip \
      ; \
      pip install pypdf~=3.15 --break-system-packages; \
    fi

RUN apt update && \
    apt install -y \
      bash-completion \
      git \
      libgcrypt20-dev \
      libpq-dev \
      p7zip \
      unzip \
    ;

RUN install-php-extensions \
    @composer \
    intl \
    opcache \
    mbstring \
    mcrypt \
    pdo_pgsql \
    xdebug \
    zip \
    ;

COPY ./devops/frankenphp/conf.d/php.${APP_ENV}.ini $PHP_INI_DIR/php.ini
COPY ./devops/frankenphp/conf.d/xdebug.ini $PHP_INI_DIR/conf.d/90-xdebug.ini
COPY ./devops/frankenphp/.bashrc /root/.bashrc

ENV APP_RUNTIME="Runtime\\FrankenPhpSymfony\\Runtime"

VOLUME /app

WORKDIR /app
```

Is it a known issue ? 
Did I do something wrong ?

Thanks,
Regards
