### ISSUE TITLE
Unexpected termination, restarting

### ISSUE THREAD

**Issue by RikudouSage** [dunglas/frankenphp#318]
I get this error after just trying to run an app in worker mode.

It prints this error all over in the log:

`{"level":"error","ts":1700923502.7101762,"msg":"unexpected termination, restarting","worker":"/app/public/index.php","exit_status":255}`

It's running in docker (using docker compose):

```yaml
  webserver:
    image: dunglas/frankenphp
    environment:
      FRANKENPHP_CONFIG: worker ./public/index.php
      APP_RUNTIME: Runtime\\FrankenPhpSymfony\\Runtime
    volumes:
      - $PWD:/app
    ports:
      - "8001:443"
```
