### ISSUE TITLE
strangely, Laravel + franken PHP not autoreload even has been implemented docker mounted volume

### ISSUE THREAD

**Issue by amirul-git** [dunglas/frankenphp#493]
So the mounted volume implementation works well using the compose.yaml code below

```
# compose.yaml

services:
  laravel:
    container_name: laravel
    # uncomment the following line if you want to use a custom Dockerfile
    build: .
    # uncomment the following line if you want to run this in a production environment
    # restart: always
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    volumes:
      - ./:/app
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - database
    # comment the following line in production, it allows to have nice human-readable logs in dev
    tty: true

# Volumes needed for Caddy certificates and configuration
volumes:
  caddy_data:
  caddy_config:
```

but strangely, when I make changes to code, the app is not reloaded in browser, I have to make manual reload to view the changes. actually when I make changes in the code, because I have implemented docker mounted volume, the changes is already maded, but on browser I still need to manually refresh it to view the change.  is it possible to make it automatic (view changes without manual reload)?
