### ISSUE TITLE
Symfony Basic Auth

### ISSUE THREAD

**Issue by chrishemmings** [dunglas/frankenphp#554]
### What happened?

Using a basic in-memory user provider in Symfony 6.3, with this Basic Http firewall configured;

```
    firewalls:
        secured_automation:
            pattern: ^/automation
            stateless: true
            http_basic: ~
            provider: in_memory
```

Calling an endpoint that matches this pattern using the curl command;

```
curl -X 'POST' \
  'https://localhost:8090/automation/check' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -k -v 
```

I get a 200 response, even though no Auth details have been passed.  The curl output looks like this.

```
> POST /automation/check HTTP/2
> Host: localhost:8090
> User-Agent: curl/8.4.0
> accept: application/json
> Content-Type: application/json
>
< HTTP/2 200
< alt-svc: h3=":8090"; ma=2592000
< server: Caddy
< date: Mon, 05 Feb 2024 20:30:32 GMT
<
* Connection #0 to host localhost left intact
```

A bit strange, but, what makes it even stranger, is, Symfony returned a 401 because authentication failed.

<img width="591" alt="image" src="https://github.com/dunglas/frankenphp/assets/7426965/9025e07d-9d2c-43a5-b487-a8e1c6a7af5d">

So, Symfony is returning a 401, and presumably the auth required headers, but, FrankenPHP doesn't seem to be forwarding this.

I can't quite work out if this is a Symfony problem, or, a FrankenPHP problem if I'm honest.  Can anyone replicate this issue?

Thanks for reading!

### Build Type

Docker (Alpine)

### Worker Mode

No

### Operating System

macOS

### CPU Architecture

x86_64
