### ISSUE TITLE
[QUESTION] Running multiple laravel in production

### ISSUE THREAD

**Issue by ezekel** [dunglas/frankenphp#814]
Hi,

I have 2 Laravel apps each app has its docker file, and I have this in my dockerfile

`ENTRYPOINT ["php", "artisan", "octane:frankenphp"]` 

after building each image I push this to my docker hub and pull it to my server

in my server, I have this 1 docker-compose only

```
  php:
    container_name: frankenphp1
    image: myusername/mycustomimage1:latest  
   
    ports:
        - "80:80" # HTTP
        - "443:443" # HTTPS
        - "443:443/udp" # HTTP/3
     
    volumes:
        - caddy_data:/data
        - caddy_config:/config
    
    entrypoint: php artisan octane:frankenphp --max-requests=1 --host=myapi.xyz.online --port=443  --admin-port=2019 --https
    environment:
        - SERVER_NAME=myapi.xyz.online



    php2:
    container_name: frankenphp2
    image: myusername/mycustomimage2:latest  
   
    ports:
        - "80:80" # HTTP
        - "443:443" # HTTPS
        - "443:443/udp" # HTTP/3
     
    volumes:
        - caddy_data:/data
        - caddy_config:/config
    
    entrypoint: php artisan octane:frankenphp --max-requests=1 --host=xyz.online --port=443  --admin-port=2019 --https
    environment:
        - SERVER_NAME=xyz.online
        
```
        
when I  spin up my container, I get this error
        
       
> Error response from daemon: driver failed programming external connectivity on endpoint frankenphp1 (a7a5d7168b11b5d684be4a41cda64fcbbda66ccabe20b19662ef3204d008ef0e): Bind for 0.0.0.0:443 failed: port is already allocated

frankenphp2 = is my main laravel app
frankenphp1 = is another Laravel app which is API only, and I use the sub-domain ( myapi )

Thank you in advance

**Comment by aungmyatmoethegreat** [comment]
Yes, the error is correct because you just exposed the same port twice.

```bash
    php:
    container_name: frankenphp1
    ports:
        - "80:80" # HTTP <= 80
        - "443:443" # HTTPS
        - "443:443/udp" # HTTP/3
     
 php2:
    container_name: frankenphp2
    image: myusername/mycustomimage2:latest  
   
    ports:
        - "80:80" # HTTP <= this
        - "443:443" # HTTPS
        - "443:443/udp" # HTTP/3
```

**Comment by ezekel** [comment]
HI @aungmyatmoethegreat

I tried like this but had no luck, the error is still the same pointing to 443

> Error response from daemon: driver failed programming external connectivity on endpoint condomain (85613b7fe9c08f8aa00d9f07e52463e7b4e50a06735a57144b7e77ed5a5e1b4d): Bind for 0.0.0.0:443 failed: port is already allocated


```
 php2:
    container_name: frankenphp2
    image: myusername/mycustomimage2:latest  
   
    ports:
        - "80:8081" # HTTP <= this
        - "443:443" # HTTPS
        - "443:443/udp" # HTTP/3
     ```   
        
also, I tried this
        
```
        ports:
        - "8081:8081" # HTTP <= this
        - "443:443" # HTTPS
        - "443:443/udp" # HTTP/3
        
```
