### ISSUE TITLE
Session handling not working in worker mode

### ISSUE THREAD

**Issue by hhoechtl** [dunglas/frankenphp#85]
I'm trying to use a bigger Symfony application in worker mode. If the caches are warm, it generally works as long as no session is used.
If I visit actions containing e.g. flash message 
```html
<div class="flashbags container">
    {% for type, messages in app.flashes %}
        ...
    {% endfor %}
</div>
```

I get this:

```
<b>Fatal error</b>:  Uncaught RuntimeException: Failed to start the session. in /app/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php:186
Stack trace:
#0 /app/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php(352): Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage-&gt;start()
#1 /app/vendor/symfony/http-foundation/Session/Session.php(261): Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage-&gt;getBag('flashes')
#2 /app/vendor/symfony/http-foundation/Session/Session.php(273): Symfony\Component\HttpFoundation\Session\Session-&gt;getBag('flashes')
#3 /app/vendor/symfony/twig-bridge/AppVariable.php(177): Symfony\Component\HttpFoundation\Session\Session-&gt;getFlashBag()
```

**Comment by withinboredom** [comment]
Which session driver are you using?

**Comment by hhoechtl** [comment]
```
    session:
        name: session-
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
        enabled: true
        storage_id: session.storage.native
        cookie_httponly: true
        gc_probability: 1
        save_path: /app/var/cache/prod_hd0b46c9c54c1cfce0c444726ba0c1595/sessions
        metadata_update_threshold: 0
```
