### ISSUE TITLE
Does frankenphp will cache the code?

### ISSUE THREAD

**Issue by ezekel** [dunglas/frankenphp#958]
Hi 
 
Using this image `FROM dunglas/frankenphp:latest`

I installed fresh Laravel + octane and when the container is up, when I edit the welcome blade it will not reflect the changes.
also, I tried to add a route in web.php when I accessed the route it showed not found. This will be reflected if I run to the container php artisan optimize. then if edited again it goes back to the problem it will not reflect.

How can I fix this?

Thank you in advance.

**Comment by sneycampos** [comment]
Could you share your entire code? docker-compose.yml and Dockerfile? Did you configure the [file watcher](https://laravel.com/docs/11.x/octane#watching-for-file-changes)?

**Comment by ezekel** [comment]
> Could you share your entire code? docker-compose.yml and Dockerfile? Did you configure the [file watcher](https://laravel.com/docs/11.x/octane#watching-for-file-changes)?

Here is my dockerfile ,docker-compose and package.json


Docker desktop version

`Docker Desktop 4.33.1 (161083)`

```
FROM dunglas/frankenphp:latest AS builder

RUN install-php-extensions \
    pdo_mysql \
    gd \
    intl \
    zip \
    opcache\
    pcntl\
    @composer



RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - \
    && apt-get install -y nodejs \
    && npm install -g npm@latest \
    && node --version \
    && npm --version

RUN apt-get update && apt-get install -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


WORKDIR /app

COPY . /app

RUN npm install


EXPOSE 5173

FROM builder  AS development

RUN composer install

ENTRYPOINT ["php", "artisan", "octane:frankenphp"]

```

docker-compose

```
    php2:
        container_name: larabells
        build:
            context: .
            dockerfile: ./docker/web.dockerfile
            target: development
        image: larabells

        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp" # HTTP/3
            - "5173:5173"
        volumes:
            - ./:/app
        entrypoint: php artisan octane:frankenphp --watch --host=larabells.local --port=443  --admin-port=2019 --https
        environment:
            - SERVER_NAME=larabells.local

        env_file:
            - ./.env
        networks:
            - mynetwork
            
 ```           

I also tried to add a watch as you mentioned above but still not working

here is my pacakte.json

```
{
    "private": true,
    "type": "module",
    "scripts": {
        "dev": "vite",
        "build": "vite build"
    },
    "devDependencies": {
        "@tailwindcss/forms": "^0.5.2",
        "alpinejs": "^3.4.2",
        "autoprefixer": "^10.4.2",
        "axios": "^1.6.4",
        "chokidar": "^3.6.0",
        "laravel-vite-plugin": "^1.0",
        "postcss": "^8.4.31",
        "tailwindcss": "^3.1.0",
        "vite": "^5.0"
    }
}

```

here is my api.php, I tried in postman but always return hello-1. even I edit it to hello-2.

```
Route::get('/books', function (Request $request) {
    return 'hello-1';
})->middleware('auth:sanctum');

```
Here is my vite.js

```
export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/js/app.js',
            ],
            refresh: true,
        }),
    ],
    server: {
        hmr: {
            host: 'localhost',
        },
        host: '0.0.0.0',
    }
});

```

Thank you in advance
