### ISSUE TITLE
Laravel HMR not working 

### ISSUE THREAD

**Issue by ezekel** [dunglas/frankenphp#965]
Hi, 

I have Laravel + Octane, but the problem the HMR will not work, I need to refresh the page just to reflect the changes.

This is how I access my site in local https://mysite.local

Thank you in advance.

**Comment by withinboredom** [comment]
Did you search existing issues? This looks related: #958

**Comment by sneycampos** [comment]
> Did you search existing issues? This looks related: #958

The related issue (#958) was from him 😂

**Comment by ezekel** [comment]
Hi,

That other thread fixed the API route when I edited the response, and when I use Postman I get the actual response, My here problem is the HMR is not working although I mentioned also in my other thread that the HMR is not working.

**Comment by sneycampos** [comment]
Could you give more details about? Your installation, watcher config etc?

**Comment by ezekel** [comment]
@sneycampos 

here is my docker-compose and dockerfile

```   
    php:
        container_name: nuxtnew
        build:
            context: .
            dockerfile: ./docker/web.dockerfile
        image: nuxtnew

        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp" 
            - "5173:5173"
        volumes:
            - .:/app 

        entrypoint: php artisan octane:frankenphp  --watch   --max-requests=250 --host=larabells.local --port=443  --admin-port=2019 --https
        environment:
            - SERVER_NAME=larabells.local
            
```

In my dockerfile

```
FROM dunglas/frankenphp:1.2.3-builder-php8.3

RUN install-php-extensions \
    pdo_mysql \
    gd \
    intl \
    zip \
    opcache\
    pcntl\
    @composer


WORKDIR /app

COPY . /app


# Install npm packages
RUN npm install



EXPOSE 5173

ENTRYPOINT ["php", "artisan", "octane:frankenphp", "--watch"]

```
